import {
  DEFAULT_EMAIL_SUMMARY_MODEL,
  DEFAULT_MAX_EMAIL_BODY_CHARS,
  PROVIDER_SUBSCRIPTION_STATUS_ACTIVE,
} from '@mail-otter/shared/constants';
import { ConnectedApplicationDAO, ProcessedMessageDAO, ProviderSubscriptionDAO } from '@/dao';
import type { ConnectedApplication, EmailQueueMessage, OAuth2Credentials, ProviderSubscription } from '@mail-otter/shared/model';
import { BadRequestError } from '@/error';
import { ConfigurationUtil } from '@mail-otter/shared/utils';
import { EmailContentUtil } from './EmailContentUtil';
import { EmailSummaryUtil } from './EmailSummaryUtil';
import { GmailProviderUtil } from './GmailProviderUtil';
import { OAuth2ProviderUtil } from './OAuth2ProviderUtil';
import { OutlookProviderUtil } from './OutlookProviderUtil';
import type { GmailMessage } from './GmailProviderUtil';
import type { OutlookMessage } from './OutlookProviderUtil';

class EmailProcessingUtil {
  public static async processQueueMessage(message: EmailQueueMessage, env: EmailProcessingEnv): Promise<void> {
    const masterKey: string = await env.AES_ENCRYPTION_KEY_SECRET.get();
    const applicationDAO = new ConnectedApplicationDAO(env.DB, masterKey);
    const application: ConnectedApplication | undefined = await applicationDAO.getById(message.applicationId);
    if (!application) {
      throw new BadRequestError('Connected application was not found for queued email event.');
    }
    if (!application.providerEmail) {
      throw new BadRequestError('Connected application does not have a provider mailbox address.');
    }

    const accessToken: string = await EmailProcessingUtil.refreshAccessToken(application, env, applicationDAO);
    if (message.type === 'gmail-notification') {
      await EmailProcessingUtil.processGmailNotification(application, accessToken, message.notificationHistoryId, env);
      return;
    }
    await EmailProcessingUtil.processOutlookMessage(application, accessToken, message.messageId, env);
  }

  private static async processGmailNotification(
    application: ConnectedApplication,
    accessToken: string,
    notificationHistoryId: string,
    env: EmailProcessingEnv,
  ): Promise<void> {
    const subscriptionDAO = new ProviderSubscriptionDAO(env.DB);
    const subscription: ProviderSubscription | undefined = await subscriptionDAO.getByApplication(application.applicationId);
    if (!subscription || subscription.status !== PROVIDER_SUBSCRIPTION_STATUS_ACTIVE) return;
    const startHistoryId: string | undefined = subscription.gmailHistoryId || notificationHistoryId;
    const history = await GmailProviderUtil.listMessageIdsSince(accessToken, startHistoryId);
    for (const messageId of history.messageIds) {
      await EmailProcessingUtil.processGmailMessage(application, accessToken, messageId, env);
    }
    await subscriptionDAO.updateGmailHistory(subscription.subscriptionId, history.historyId || notificationHistoryId);
  }

  private static async processGmailMessage(
    application: ConnectedApplication,
    accessToken: string,
    messageId: string,
    env: EmailProcessingEnv,
  ): Promise<void> {
    const message: GmailMessage = await GmailProviderUtil.getMessage(accessToken, messageId);
    const headers = message.payload?.headers;
    const subject: string = EmailContentUtil.getHeader(headers, 'Subject') || '(no subject)';
    const from: string = EmailContentUtil.getHeader(headers, 'From') || '';
    const isSummary: boolean = EmailContentUtil.getHeader(headers, 'X-Mail-Otter-Summary')?.toLowerCase() === 'true';
    const processedDAO = new ProcessedMessageDAO(env.DB);
    const started: boolean = await processedDAO.tryStart(
      application.applicationId,
      application.providerId,
      message.id,
      message.threadId,
      subject,
    );
    if (!started) return;
    try {
      if (isSummary || EmailContentUtil.isFromMailbox(from, application.providerEmail)) {
        await processedDAO.markSkipped(application.applicationId, message.id, 'Message was generated by the mailbox owner or Mail-Otter.');
        return;
      }
      const extracted = EmailContentUtil.extractGmailText(message.payload);
      const summary: string = await EmailProcessingUtil.summarize(env, subject, from, extracted.text);
      await GmailProviderUtil.sendSummaryReply(accessToken, application.providerEmail!, message, summary);
      await processedDAO.markSummarized(application.applicationId, message.id);
    } catch (error: unknown) {
      await processedDAO.markError(application.applicationId, message.id, EmailProcessingUtil.formatError(error));
      throw error;
    }
  }

  private static async processOutlookMessage(
    application: ConnectedApplication,
    accessToken: string,
    messageId: string,
    env: EmailProcessingEnv,
  ): Promise<void> {
    const message: OutlookMessage = await OutlookProviderUtil.getMessage(accessToken, messageId);
    const from: string = message.from?.emailAddress?.address || message.sender?.emailAddress?.address || '';
    const subject: string = message.subject || '(no subject)';
    const isSummary: boolean =
      message.internetMessageHeaders?.some(
        (header: { name: string; value: string }): boolean =>
          header.name.toLowerCase() === 'x-mail-otter-summary' && header.value.toLowerCase() === 'true',
      ) ?? false;
    const processedDAO = new ProcessedMessageDAO(env.DB);
    const started: boolean = await processedDAO.tryStart(
      application.applicationId,
      application.providerId,
      message.id,
      message.conversationId || null,
      subject,
    );
    if (!started) return;
    try {
      if (isSummary || EmailContentUtil.isFromMailbox(from, application.providerEmail)) {
        await processedDAO.markSkipped(application.applicationId, message.id, 'Message was generated by the mailbox owner or Mail-Otter.');
        return;
      }
      const body: string = OutlookProviderUtil.getMessageText(message);
      const summary: string = await EmailProcessingUtil.summarize(env, subject, from, body);
      await OutlookProviderUtil.sendSelfSummaryReply(accessToken, message.id, application.providerEmail!, summary);
      await processedDAO.markSummarized(application.applicationId, message.id);
    } catch (error: unknown) {
      await processedDAO.markError(application.applicationId, message.id, EmailProcessingUtil.formatError(error));
      throw error;
    }
  }

  private static async refreshAccessToken(
    application: ConnectedApplication,
    env: EmailProcessingEnv,
    applicationDAO: ConnectedApplicationDAO,
  ): Promise<string> {
    const credentials = application.credentials as OAuth2Credentials;
    const tokenResult = await OAuth2ProviderUtil.refreshAccessToken({
      providerId: application.providerId,
      credentials,
    });
    if (tokenResult.refreshToken) {
      await applicationDAO.updateOAuth2RefreshToken(application.applicationId, tokenResult.refreshToken);
    }
    return tokenResult.accessToken;
  }

  private static async summarize(env: EmailProcessingEnv, subject: string, from: string, body: string): Promise<string> {
    const maxChars: number = ConfigurationUtil.getPositiveInteger(env.MAX_EMAIL_BODY_CHARS, DEFAULT_MAX_EMAIL_BODY_CHARS);
    const input: string = EmailContentUtil.truncate(body || '(empty message body)', maxChars);
    return EmailSummaryUtil.summarizeEmail(env.AI, env.AI_SUMMARY_MODEL || DEFAULT_EMAIL_SUMMARY_MODEL, subject, from, input);
  }

  private static formatError(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
  }
}

interface EmailProcessingEnv {
  DB: D1Database;
  AES_ENCRYPTION_KEY_SECRET: SecretsStoreSecret;
  AI: Ai;
  AI_SUMMARY_MODEL?: string | undefined;
  MAX_EMAIL_BODY_CHARS?: string | undefined;
}

export { EmailProcessingUtil };
export type { EmailProcessingEnv };
