const DEFAULT_MAX_APPLICATIONS_PER_USER = '99';
const DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES = '15';
const DEFAULT_GMAIL_WATCH_RENEWAL_WINDOW_HOURS = '48';
const DEFAULT_OUTLOOK_SUBSCRIPTION_RENEWAL_WINDOW_HOURS = '24';
const DEFAULT_OUTLOOK_SUBSCRIPTION_TTL_DAYS = '6';
const DEFAULT_EMAIL_SUMMARY_MODEL = '@cf/meta/llama-3.1-8b-instruct';
const DEFAULT_MAX_EMAIL_BODY_CHARS = '12000';

export {
  DEFAULT_EMAIL_SUMMARY_MODEL,
  DEFAULT_GMAIL_WATCH_RENEWAL_WINDOW_HOURS,
  DEFAULT_MAX_EMAIL_BODY_CHARS,
  DEFAULT_MAX_APPLICATIONS_PER_USER,
  DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES,
  DEFAULT_OUTLOOK_SUBSCRIPTION_RENEWAL_WINDOW_HOURS,
  DEFAULT_OUTLOOK_SUBSCRIPTION_TTL_DAYS,
};
