// Central owner of provider_application_configs row keys (D1 `provider_application_configs` table).
// Digest keys intentionally mirror the DIGEST_CONFIG_KEY_* values in `@mail-otter/shared/constants`
// so DAO code has a single import location; keep both in sync if values ever change.

const PROVIDER_CONFIG_KEY_ATTACHMENT_VISION_ENABLED = 'attachment_vision_enabled';
const PROVIDER_CONFIG_KEY_AUTO_EXECUTE_ACTION_TYPES = 'auto_execute_action_types';
const PROVIDER_CONFIG_KEY_CALENDAR_TIME_ZONE = 'calendar_time_zone';
const PROVIDER_CONFIG_KEY_CONTENT_LANGUAGE = 'content_language';
const PROVIDER_CONFIG_KEY_DIGEST_ENABLED = 'digest_enabled';
const PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT = 'digest_last_sent_at';
const PROVIDER_CONFIG_KEY_DIGEST_SECTIONS = 'digest_sections';
const PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME = 'digest_send_time';
const PROVIDER_CONFIG_KEY_EMAIL_PROCESSING_RULES = 'email_processing_rules';
const PROVIDER_CONFIG_KEY_GMAIL_PUBSUB_TOPIC_NAME = 'gmail_pubsub_topic_name';
const PROVIDER_CONFIG_KEY_GOOGLE_DRIVE_PAGE_TOKEN = 'google_drive_page_token';
const PROVIDER_CONFIG_KEY_IMAP_HOST = 'imap_host';
const PROVIDER_CONFIG_KEY_IMAP_PORT = 'imap_port';
const PROVIDER_CONFIG_KEY_IMAP_USERNAME = 'imap_username';
const PROVIDER_CONFIG_KEY_OAUTH2_ENABLED_FEATURES = 'oauth2_enabled_features';
const PROVIDER_CONFIG_KEY_ONEDRIVE_DELTA_LINK = 'onedrive_delta_link';
const PROVIDER_CONFIG_KEY_SENDER_DOMAIN_FILTERS = 'sender_domain_filters';
const PROVIDER_CONFIG_KEY_SMTP_HOST = 'smtp_host';
const PROVIDER_CONFIG_KEY_SMTP_PORT = 'smtp_port';

export {
  PROVIDER_CONFIG_KEY_ATTACHMENT_VISION_ENABLED,
  PROVIDER_CONFIG_KEY_AUTO_EXECUTE_ACTION_TYPES,
  PROVIDER_CONFIG_KEY_CALENDAR_TIME_ZONE,
  PROVIDER_CONFIG_KEY_CONTENT_LANGUAGE,
  PROVIDER_CONFIG_KEY_DIGEST_ENABLED,
  PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT,
  PROVIDER_CONFIG_KEY_DIGEST_SECTIONS,
  PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME,
  PROVIDER_CONFIG_KEY_EMAIL_PROCESSING_RULES,
  PROVIDER_CONFIG_KEY_GMAIL_PUBSUB_TOPIC_NAME,
  PROVIDER_CONFIG_KEY_GOOGLE_DRIVE_PAGE_TOKEN,
  PROVIDER_CONFIG_KEY_IMAP_HOST,
  PROVIDER_CONFIG_KEY_IMAP_PORT,
  PROVIDER_CONFIG_KEY_IMAP_USERNAME,
  PROVIDER_CONFIG_KEY_OAUTH2_ENABLED_FEATURES,
  PROVIDER_CONFIG_KEY_ONEDRIVE_DELTA_LINK,
  PROVIDER_CONFIG_KEY_SENDER_DOMAIN_FILTERS,
  PROVIDER_CONFIG_KEY_SMTP_HOST,
  PROVIDER_CONFIG_KEY_SMTP_PORT,
};
