import { GetAnalyticsRoute as OriginalGetAnalyticsRoute } from './user/analytics/GET';
import { GetCurrentUserRoute as OriginalGetCurrentUserRoute } from './user/me/GET';
import { UpdateCurrentUserRoute as OriginalUpdateCurrentUserRoute } from './user/me/PUT';
import { ListApplicationsRoute as OriginalListApplicationsRoute } from './user/applications/GET';
import { CreateApplicationRoute as OriginalCreateApplicationRoute } from './user/application/POST';
import { UpdateApplicationRoute as OriginalUpdateApplicationRoute } from './user/application/PUT';
import { DeleteApplicationRoute as OriginalDeleteApplicationRoute } from './user/application/DELETE';
import { UpdateApplicationContextRoute as OriginalUpdateApplicationContextRoute } from './user/application/context/PUT';
import { DismissApplicationErrorRoute as OriginalDismissApplicationErrorRoute } from './user/application/dismiss-error/POST';
import { DeleteApplicationContextDocumentsRoute as OriginalDeleteApplicationContextDocumentsRoute } from './user/application/context/delete-documents/POST';
import { ListApplicationContextDocumentsRoute as OriginalListApplicationContextDocumentsRoute } from './user/application/context/documents/GET';
import { ListApplicationContextDeletionRunsRoute as OriginalListApplicationContextDeletionRunsRoute } from './user/application/context/deletions/GET';
import { GetApplicationContextDocumentProviderLinkRoute as OriginalGetApplicationContextDocumentProviderLinkRoute } from './user/application/context/document/provider-link/GET';
import { ListContextDocumentAuditLogsRoute as OriginalListContextDocumentAuditLogsRoute } from './user/application/context/document/audit-logs/GET';
import { ListEmailActionsRoute as OriginalListEmailActionsRoute } from './user/actions/GET';
import { ListEmailActionExecutionsRoute as OriginalListEmailActionExecutionsRoute } from './user/actions/executions/GET';
import { ExecuteUserEmailActionRoute as OriginalExecuteUserEmailActionRoute } from './user/actions/execute/POST';
import { SnoozeEmailActionRoute as OriginalSnoozeEmailActionRoute } from './user/actions/snooze/POST';
import { ScheduleEmailActionRoute as OriginalScheduleEmailActionRoute } from './user/actions/schedule/POST';
import { GetApplicationFoldersRoute as OriginalGetApplicationFoldersRoute } from './user/application/folders/GET';
import { UpdateApplicationWatchSettingsRoute as OriginalUpdateApplicationWatchSettingsRoute } from './user/application/watch-settings/PUT';
import { CreateOAuth2AuthorizationRoute as OriginalCreateOAuth2AuthorizationRoute } from './user/application/oauth2/authorize/POST';
import { StartApplicationWatchRoute as OriginalStartApplicationWatchRoute } from './user/application/watch/POST';
import { StopApplicationWatchRoute as OriginalStopApplicationWatchRoute } from './user/application/stop/POST';
import { ListIntegrationsRoute as OriginalListIntegrationsRoute } from './user/application/integrations/GET';
import { CreateIntegrationRoute as OriginalCreateIntegrationRoute } from './user/application/integrations/POST';
import { UpdateIntegrationRoute as OriginalUpdateIntegrationRoute } from './user/application/integrations/PUT';
import { DeleteIntegrationRoute as OriginalDeleteIntegrationRoute } from './user/application/integrations/DELETE';
import { TestIntegrationRoute as OriginalTestIntegrationRoute } from './user/application/integrations/test/POST';
import { ListIntegrationDeliveriesRoute as OriginalListIntegrationDeliveriesRoute } from './user/application/integrations/deliveries/GET';
import { GetApplicationRulesRoute as OriginalGetApplicationRulesRoute } from './user/application/rules/GET';
import { UpdateApplicationRulesRoute as OriginalUpdateApplicationRulesRoute } from './user/application/rules/PUT';
import { SuggestApplicationRuleRoute as OriginalSuggestApplicationRuleRoute } from './user/application/rules/suggest/POST';
import { GetApplicationLabelsRoute as OriginalGetApplicationLabelsRoute } from './user/application/labels/GET';
import { GetDigestConfigRoute as OriginalGetDigestConfigRoute } from './user/application/digest/GET';
import { UpdateDigestConfigRoute as OriginalUpdateDigestConfigRoute } from './user/application/digest/PUT';
import { SendDigestNowRoute as OriginalSendDigestNowRoute } from './user/application/digest/send/POST';
import { OAuth2CallbackRoute as OriginalOAuth2CallbackRoute } from './api/oauth2/callback/GET';
import { GetActionConfirmationRoute as OriginalGetActionConfirmationRoute } from './api/actions/GET';
import { ExecuteActionCallbackRoute as OriginalExecuteActionCallbackRoute } from './api/actions/execute/POST';
import { FastmailWebhookRoute as OriginalFastmailWebhookRoute } from './api/webhooks/fastmail/POST';
import { GmailWebhookRoute as OriginalGmailWebhookRoute } from './api/webhooks/gmail/POST';
import { OutlookWebhookRoute as OriginalOutlookWebhookRoute } from './api/webhooks/outlook/POST';
import { OutlookLifecycleWebhookRoute as OriginalOutlookLifecycleWebhookRoute } from './api/webhooks/outlook/lifecycle/POST';

import { ListBackgroundTaskRunsRoute as OriginalListBackgroundTaskRunsRoute } from './user/processing/task-runs/GET';
import { ListProcessingCalendarEventsRoute as OriginalListProcessingCalendarEventsRoute } from './user/processing/calendar-events/GET';
import { ListProcessedMessagesRoute as OriginalListProcessedMessagesRoute } from './user/processing/messages/GET';
import { RunTaskNowRoute as OriginalRunTaskNowRoute } from './user/processing/run-task/POST';
import { ListActivityRoute as OriginalListActivityRoute } from './user/activity/GET';
import { ChatRoute as OriginalChatRoute } from './user/chat/POST';

export const GetAnalyticsRoute: typeof OriginalGetAnalyticsRoute = OriginalGetAnalyticsRoute;
export const GetCurrentUserRoute: typeof OriginalGetCurrentUserRoute = OriginalGetCurrentUserRoute;
export const UpdateCurrentUserRoute: typeof OriginalUpdateCurrentUserRoute = OriginalUpdateCurrentUserRoute;
export const ListApplicationsRoute: typeof OriginalListApplicationsRoute = OriginalListApplicationsRoute;
export const CreateApplicationRoute: typeof OriginalCreateApplicationRoute = OriginalCreateApplicationRoute;
export const UpdateApplicationRoute: typeof OriginalUpdateApplicationRoute = OriginalUpdateApplicationRoute;
export const DeleteApplicationRoute: typeof OriginalDeleteApplicationRoute = OriginalDeleteApplicationRoute;
export const UpdateApplicationContextRoute: typeof OriginalUpdateApplicationContextRoute = OriginalUpdateApplicationContextRoute;
export const DismissApplicationErrorRoute: typeof OriginalDismissApplicationErrorRoute = OriginalDismissApplicationErrorRoute;
export const DeleteApplicationContextDocumentsRoute: typeof OriginalDeleteApplicationContextDocumentsRoute =
  OriginalDeleteApplicationContextDocumentsRoute;
export const ListApplicationContextDocumentsRoute: typeof OriginalListApplicationContextDocumentsRoute =
  OriginalListApplicationContextDocumentsRoute;
export const ListApplicationContextDeletionRunsRoute: typeof OriginalListApplicationContextDeletionRunsRoute =
  OriginalListApplicationContextDeletionRunsRoute;
export const GetApplicationContextDocumentProviderLinkRoute: typeof OriginalGetApplicationContextDocumentProviderLinkRoute =
  OriginalGetApplicationContextDocumentProviderLinkRoute;
export const ListContextDocumentAuditLogsRoute: typeof OriginalListContextDocumentAuditLogsRoute =
  OriginalListContextDocumentAuditLogsRoute;
export const ListEmailActionsRoute: typeof OriginalListEmailActionsRoute = OriginalListEmailActionsRoute;
export const ListEmailActionExecutionsRoute: typeof OriginalListEmailActionExecutionsRoute = OriginalListEmailActionExecutionsRoute;
export const ExecuteUserEmailActionRoute: typeof OriginalExecuteUserEmailActionRoute = OriginalExecuteUserEmailActionRoute;
export const SnoozeEmailActionRoute: typeof OriginalSnoozeEmailActionRoute = OriginalSnoozeEmailActionRoute;
export const ScheduleEmailActionRoute: typeof OriginalScheduleEmailActionRoute = OriginalScheduleEmailActionRoute;
export const GetApplicationFoldersRoute: typeof OriginalGetApplicationFoldersRoute = OriginalGetApplicationFoldersRoute;
export const UpdateApplicationWatchSettingsRoute: typeof OriginalUpdateApplicationWatchSettingsRoute =
  OriginalUpdateApplicationWatchSettingsRoute;
export const CreateOAuth2AuthorizationRoute: typeof OriginalCreateOAuth2AuthorizationRoute = OriginalCreateOAuth2AuthorizationRoute;
export const StartApplicationWatchRoute: typeof OriginalStartApplicationWatchRoute = OriginalStartApplicationWatchRoute;
export const StopApplicationWatchRoute: typeof OriginalStopApplicationWatchRoute = OriginalStopApplicationWatchRoute;
export const OAuth2CallbackRoute: typeof OriginalOAuth2CallbackRoute = OriginalOAuth2CallbackRoute;
export const GetActionConfirmationRoute: typeof OriginalGetActionConfirmationRoute = OriginalGetActionConfirmationRoute;
export const ExecuteActionCallbackRoute: typeof OriginalExecuteActionCallbackRoute = OriginalExecuteActionCallbackRoute;
export const FastmailWebhookRoute: typeof OriginalFastmailWebhookRoute = OriginalFastmailWebhookRoute;
export const GmailWebhookRoute: typeof OriginalGmailWebhookRoute = OriginalGmailWebhookRoute;
export const OutlookWebhookRoute: typeof OriginalOutlookWebhookRoute = OriginalOutlookWebhookRoute;
export const OutlookLifecycleWebhookRoute: typeof OriginalOutlookLifecycleWebhookRoute = OriginalOutlookLifecycleWebhookRoute;
export const ListIntegrationsRoute: typeof OriginalListIntegrationsRoute = OriginalListIntegrationsRoute;
export const CreateIntegrationRoute: typeof OriginalCreateIntegrationRoute = OriginalCreateIntegrationRoute;
export const UpdateIntegrationRoute: typeof OriginalUpdateIntegrationRoute = OriginalUpdateIntegrationRoute;
export const DeleteIntegrationRoute: typeof OriginalDeleteIntegrationRoute = OriginalDeleteIntegrationRoute;
export const TestIntegrationRoute: typeof OriginalTestIntegrationRoute = OriginalTestIntegrationRoute;
export const ListIntegrationDeliveriesRoute: typeof OriginalListIntegrationDeliveriesRoute = OriginalListIntegrationDeliveriesRoute;
export const GetApplicationRulesRoute: typeof OriginalGetApplicationRulesRoute = OriginalGetApplicationRulesRoute;
export const UpdateApplicationRulesRoute: typeof OriginalUpdateApplicationRulesRoute = OriginalUpdateApplicationRulesRoute;
export const SuggestApplicationRuleRoute: typeof OriginalSuggestApplicationRuleRoute = OriginalSuggestApplicationRuleRoute;
export const GetApplicationLabelsRoute: typeof OriginalGetApplicationLabelsRoute = OriginalGetApplicationLabelsRoute;
export const GetDigestConfigRoute: typeof OriginalGetDigestConfigRoute = OriginalGetDigestConfigRoute;
export const UpdateDigestConfigRoute: typeof OriginalUpdateDigestConfigRoute = OriginalUpdateDigestConfigRoute;
export const SendDigestNowRoute: typeof OriginalSendDigestNowRoute = OriginalSendDigestNowRoute;
export const ListBackgroundTaskRunsRoute: typeof OriginalListBackgroundTaskRunsRoute = OriginalListBackgroundTaskRunsRoute;
export const ListProcessingCalendarEventsRoute: typeof OriginalListProcessingCalendarEventsRoute =
  OriginalListProcessingCalendarEventsRoute;
export const ListProcessedMessagesRoute: typeof OriginalListProcessedMessagesRoute = OriginalListProcessedMessagesRoute;
export const RunTaskNowRoute: typeof OriginalRunTaskNowRoute = OriginalRunTaskNowRoute;
export const ListActivityRoute: typeof OriginalListActivityRoute = OriginalListActivityRoute;
export const ChatRoute: typeof OriginalChatRoute = OriginalChatRoute;
