import { beforeEach, describe, expect, it, vi } from 'vitest';
import {
  DIGEST_CONFIG_KEY_ENABLED,
  DIGEST_CONFIG_KEY_LAST_SENT_AT,
  DIGEST_CONFIG_KEY_SECTIONS,
  DIGEST_CONFIG_KEY_SEND_TIME,
} from '@mail-otter/shared/constants';
import {
  PROVIDER_CONFIG_KEY_ATTACHMENT_VISION_ENABLED,
  PROVIDER_CONFIG_KEY_AUTO_EXECUTE_ACTION_TYPES,
  PROVIDER_CONFIG_KEY_CALENDAR_TIME_ZONE,
  PROVIDER_CONFIG_KEY_CONTENT_LANGUAGE,
  PROVIDER_CONFIG_KEY_DIGEST_ENABLED,
  PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT,
  PROVIDER_CONFIG_KEY_DIGEST_SECTIONS,
  PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME,
  PROVIDER_CONFIG_KEY_EMAIL_PROCESSING_RULES,
  PROVIDER_CONFIG_KEY_GMAIL_PUBSUB_TOPIC_NAME,
  PROVIDER_CONFIG_KEY_GOOGLE_DRIVE_PAGE_TOKEN,
  PROVIDER_CONFIG_KEY_IMAP_HOST,
  PROVIDER_CONFIG_KEY_IMAP_PORT,
  PROVIDER_CONFIG_KEY_IMAP_USERNAME,
  PROVIDER_CONFIG_KEY_OAUTH2_ENABLED_FEATURES,
  PROVIDER_CONFIG_KEY_ONEDRIVE_DELTA_LINK,
  PROVIDER_CONFIG_KEY_SENDER_DOMAIN_FILTERS,
  PROVIDER_CONFIG_KEY_SMTP_HOST,
  PROVIDER_CONFIG_KEY_SMTP_PORT,
} from '@mail-otter/backend-data/constants';

describe('ProviderConfigKeys', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('defines the documented provider-application config row keys', () => {
    expect(PROVIDER_CONFIG_KEY_CALENDAR_TIME_ZONE).toBe('calendar_time_zone');
    expect(PROVIDER_CONFIG_KEY_CONTENT_LANGUAGE).toBe('content_language');
    expect(PROVIDER_CONFIG_KEY_ATTACHMENT_VISION_ENABLED).toBe('attachment_vision_enabled');
    expect(PROVIDER_CONFIG_KEY_SENDER_DOMAIN_FILTERS).toBe('sender_domain_filters');
    expect(PROVIDER_CONFIG_KEY_GOOGLE_DRIVE_PAGE_TOKEN).toBe('google_drive_page_token');
    expect(PROVIDER_CONFIG_KEY_ONEDRIVE_DELTA_LINK).toBe('onedrive_delta_link');
    expect(PROVIDER_CONFIG_KEY_DIGEST_ENABLED).toBe('digest_enabled');
    expect(PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME).toBe('digest_send_time');
    expect(PROVIDER_CONFIG_KEY_DIGEST_SECTIONS).toBe('digest_sections');
    expect(PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT).toBe('digest_last_sent_at');
  });

  it('defines connection, feature, and automation keys', () => {
    expect(PROVIDER_CONFIG_KEY_GMAIL_PUBSUB_TOPIC_NAME).toBe('gmail_pubsub_topic_name');
    expect(PROVIDER_CONFIG_KEY_OAUTH2_ENABLED_FEATURES).toBe('oauth2_enabled_features');
    expect(PROVIDER_CONFIG_KEY_IMAP_HOST).toBe('imap_host');
    expect(PROVIDER_CONFIG_KEY_IMAP_PORT).toBe('imap_port');
    expect(PROVIDER_CONFIG_KEY_IMAP_USERNAME).toBe('imap_username');
    expect(PROVIDER_CONFIG_KEY_SMTP_HOST).toBe('smtp_host');
    expect(PROVIDER_CONFIG_KEY_SMTP_PORT).toBe('smtp_port');
    expect(PROVIDER_CONFIG_KEY_AUTO_EXECUTE_ACTION_TYPES).toBe('auto_execute_action_types');
    expect(PROVIDER_CONFIG_KEY_EMAIL_PROCESSING_RULES).toBe('email_processing_rules');
  });

  it('keeps every key value unique', () => {
    const values = [
      PROVIDER_CONFIG_KEY_ATTACHMENT_VISION_ENABLED,
      PROVIDER_CONFIG_KEY_AUTO_EXECUTE_ACTION_TYPES,
      PROVIDER_CONFIG_KEY_CALENDAR_TIME_ZONE,
      PROVIDER_CONFIG_KEY_CONTENT_LANGUAGE,
      PROVIDER_CONFIG_KEY_DIGEST_ENABLED,
      PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT,
      PROVIDER_CONFIG_KEY_DIGEST_SECTIONS,
      PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME,
      PROVIDER_CONFIG_KEY_EMAIL_PROCESSING_RULES,
      PROVIDER_CONFIG_KEY_GMAIL_PUBSUB_TOPIC_NAME,
      PROVIDER_CONFIG_KEY_GOOGLE_DRIVE_PAGE_TOKEN,
      PROVIDER_CONFIG_KEY_IMAP_HOST,
      PROVIDER_CONFIG_KEY_IMAP_PORT,
      PROVIDER_CONFIG_KEY_IMAP_USERNAME,
      PROVIDER_CONFIG_KEY_OAUTH2_ENABLED_FEATURES,
      PROVIDER_CONFIG_KEY_ONEDRIVE_DELTA_LINK,
      PROVIDER_CONFIG_KEY_SENDER_DOMAIN_FILTERS,
      PROVIDER_CONFIG_KEY_SMTP_HOST,
      PROVIDER_CONFIG_KEY_SMTP_PORT,
    ];
    expect(new Set(values).size).toBe(values.length);
  });

  it('stays in sync with the shared digest config key values', () => {
    expect(PROVIDER_CONFIG_KEY_DIGEST_ENABLED).toBe(DIGEST_CONFIG_KEY_ENABLED);
    expect(PROVIDER_CONFIG_KEY_DIGEST_SEND_TIME).toBe(DIGEST_CONFIG_KEY_SEND_TIME);
    expect(PROVIDER_CONFIG_KEY_DIGEST_SECTIONS).toBe(DIGEST_CONFIG_KEY_SECTIONS);
    expect(PROVIDER_CONFIG_KEY_DIGEST_LAST_SENT_AT).toBe(DIGEST_CONFIG_KEY_LAST_SENT_AT);
  });
});
